# H2 Database Configuration for Testing
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Disable unique name generation for the datasource to ensure the same in-memory database is used across tests
spring.datasource.generate-unique-name=false

# Enable H2 console for testing purposes
spring.h2.console.enabled=true

# Hibernate Configuration for Testing
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Allow access to H2 console from other hosts
spring.h2.console.settings.web-allow-others=true

# Render real IP addresses when behind a proxy
server.forward-headers-strategy=framework